pragma Singleton

import qs.services
import qs.utils
import Quickshell
import Quickshell.Io
import QtQuick

Singleton {
    id: root

    // Theme ID to Ghostty theme mapping
    readonly property var ghosttyThemes: ({
        "gruvbox-dark": "Gruvbox Dark",
        "gruvbox-light": "Gruvbox Light"
    })

    // Theme ID to NvChad theme mapping
    readonly property var nvimThemes: ({
        "gruvbox-dark": "gruvbox",
        "gruvbox-light": "gruvbox_light"
    })

    // Niri border colors per theme
    readonly property var niriBorderColors: ({
        "gruvbox-dark": { active: "#d79921", inactive: "#928374" },
        "gruvbox-light": { active: "#b57614", inactive: "#928374" }
    })

    // Zen browser CSS variables per theme
    readonly property var zenColors: ({
        "gruvbox-dark": {
            bg: "#1d2021",
            fg: "#ebdbb2",
            primary: "#d79921",
            secondary: "#689d6a",
            accent: "#b16286"
        },
        "gruvbox-light": {
            bg: "#fbf1c7",
            fg: "#3c3836",
            primary: "#b57614",
            secondary: "#427b58",
            accent: "#8f3f71"
        }
    })

    // Connect to theme changes
    Connections {
        target: Theme
        function onThemeChanged() {
            root.propagateTheme();
        }
    }

    function propagateTheme() {
        const themeId = Theme.currentThemeId;
        console.log("ThemePropagator: Propagating theme:", themeId);

        updateGhostty(themeId);
        updateNeovim(themeId);
        updateNiri(themeId);
        updateZen(themeId);
    }

    // ============ Ghostty ============
    function updateGhostty(themeId) {
        const themeName = ghosttyThemes[themeId] || "Gruvbox Dark";
        const configContent = `# Auto-generated by Caelestia ThemePropagator
# Do not edit - this file is overwritten on theme change
theme = ${themeName}
`;
        ghosttyConfig.setText(configContent);
    }

    FileView {
        id: ghosttyConfig
        path: `${Paths.home}/.config/ghostty/theme.conf`
        onTextChanged: {
            // After writing, send SIGUSR1 to ghostty for live reload
            ghosttyReloadProc.running = true;
        }
    }

    Process {
        id: ghosttyReloadProc
        command: ["pkill", "-USR1", "ghostty"]
        onExited: (exitCode, exitStatus) => {
            if (exitCode === 0) {
                console.log("ThemePropagator: Ghostty theme reloaded");
            }
        }
    }

    // ============ Neovim ============
    function updateNeovim(themeId) {
        const themeName = nvimThemes[themeId] || "gruvbox";
        const stateContent = JSON.stringify({
            theme: themeName,
            themeId: themeId,
            timestamp: Date.now()
        }, null, 2);
        nvimState.setText(stateContent);
    }

    FileView {
        id: nvimState
        path: `${Paths.state}/nvim-theme.json`
        onTextChanged: {
            // After writing state, send command to nvim via socket
            nvimReloadProc.running = true;
        }
    }

    Process {
        id: nvimReloadProc
        command: ["bash", "-c", `
            for sock in /tmp/nvim*.sock /run/user/$(id -u)/nvim*.sock; do
                [ -S "$sock" ] && nvim --server "$sock" --remote-send '<Cmd>lua require("caelestia-theme").reload()<CR>' 2>/dev/null
            done
        `]
        onExited: (exitCode, exitStatus) => {
            console.log("ThemePropagator: Neovim reload attempted");
        }
    }

    // ============ Niri ============
    function updateNiri(themeId) {
        const colors = niriBorderColors[themeId] || niriBorderColors["gruvbox-dark"];

        // Read template, inject colors, write KDL config
        niriTemplateLoader.colors = colors;
        niriTemplateLoader.reload();
    }

    FileView {
        id: niriTemplateLoader
        property var colors: null
        path: `${Paths.home}/.config/niri/config-template.json`

        onLoaded: {
            if (!colors) return;
            try {
                const template = JSON.parse(text());
                generateNiriKdl(template, colors);
            } catch (e) {
                console.error("ThemePropagator: Failed to parse niri template:", e);
            }
        }
        onLoadFailed: err => {
            console.warn("ThemePropagator: No niri template found, skipping niri update");
        }
    }

    function generateNiriKdl(template, colors) {
        // Build KDL config from template + injected colors
        let kdl = `// Auto-generated by Caelestia ThemePropagator
// Do not edit directly - modify config-template.json instead

`;
        // Outputs
        if (template.outputs) {
            for (const [name, config] of Object.entries(template.outputs)) {
                kdl += `output "${name}" {\n`;
                if (config.position) {
                    kdl += `    position x=${config.position.x} y=${config.position.y}\n`;
                }
                kdl += `}\n\n`;
            }
        }

        // General settings
        if (template.preferNoCsd) {
            kdl += `prefer-no-csd\n\n`;
        }

        if (template.screenshotPath) {
            kdl += `screenshot-path "${template.screenshotPath}"\n\n`;
        }

        // Input
        if (template.input) {
            kdl += `input {\n`;
            if (template.input.keyboard?.xkb) {
                kdl += `    keyboard {\n`;
                kdl += `        xkb {\n`;
                if (template.input.keyboard.xkb.layout) {
                    kdl += `            layout "${template.input.keyboard.xkb.layout}"\n`;
                }
                kdl += `        }\n`;
                kdl += `    }\n`;
            }
            if (template.input.touchpad) {
                kdl += `    touchpad {\n`;
                if (template.input.touchpad.tap) kdl += `        tap\n`;
                if (template.input.touchpad.naturalScroll) kdl += `        natural-scroll\n`;
                kdl += `    }\n`;
            }
            kdl += `}\n\n`;
        }

        // Layout with dynamic border colors
        kdl += `layout {\n`;
        if (template.layout?.gaps !== undefined) {
            kdl += `    gaps ${template.layout.gaps}\n`;
        }
        if (template.layout?.shadow?.enable) {
            kdl += `    shadow {\n        on\n    }\n`;
        }
        if (template.layout?.struts) {
            const s = template.layout.struts;
            kdl += `    struts {\n`;
            if (s.top) kdl += `        top ${s.top}\n`;
            if (s.left) kdl += `        left ${s.left}\n`;
            if (s.right) kdl += `        right ${s.right}\n`;
            if (s.bottom) kdl += `        bottom ${s.bottom}\n`;
            kdl += `    }\n`;
        }
        // Border with dynamic colors
        kdl += `    border {\n`;
        kdl += `        on\n`;
        kdl += `        width ${template.layout?.border?.width || 2}\n`;
        kdl += `        active-color "${colors.active}"\n`;
        kdl += `        inactive-color "${colors.inactive}"\n`;
        kdl += `    }\n`;
        kdl += `}\n\n`;

        // Window rules
        if (template.windowRules) {
            for (const rule of template.windowRules) {
                kdl += `window-rule {\n`;
                if (rule.geometryCornerRadius) {
                    const r = rule.geometryCornerRadius;
                    kdl += `    geometry-corner-radius ${r} ${r} ${r} ${r}\n`;
                }
                if (rule.clipToGeometry) {
                    kdl += `    clip-to-geometry true\n`;
                }
                kdl += `}\n\n`;
            }
        }

        // Animations
        if (template.animations) {
            kdl += `animations {\n`;
            if (template.animations.workspaceSwitch?.enable === false) {
                kdl += `    workspace-switch {\n        off\n    }\n`;
            }
            kdl += `}\n\n`;
        }

        // Binds
        if (template.binds) {
            kdl += `binds {\n`;
            for (const [key, bind] of Object.entries(template.binds)) {
                const action = Object.keys(bind.action)[0];
                const args = bind.action[action];
                if (Array.isArray(args) && args.length > 0) {
                    if (action === "spawn") {
                        kdl += `    ${key} { spawn ${args.map(a => `"${a}"`).join(" ")}; }\n`;
                    } else {
                        kdl += `    ${key} { ${action} ${args.join(" ")}; }\n`;
                    }
                } else {
                    kdl += `    ${key} { ${action}; }\n`;
                }
            }
            kdl += `}\n\n`;
        }

        // Spawn at startup
        if (template.spawnAtStartup) {
            for (const item of template.spawnAtStartup) {
                if (item.command) {
                    kdl += `spawn-at-startup ${item.command.map(c => `"${c}"`).join(" ")}\n`;
                }
            }
        }

        niriConfig.setText(kdl);
    }

    FileView {
        id: niriConfig
        path: `${Paths.home}/.config/niri/caelestia-config.kdl`
        onTextChanged: {
            // Trigger niri config reload
            niriReloadProc.running = true;
        }
    }

    Process {
        id: niriReloadProc
        command: ["niri", "msg", "action", "reload-config-or-panic"]
        onExited: (exitCode, exitStatus) => {
            if (exitCode === 0) {
                console.log("ThemePropagator: Niri config reloaded");
            } else {
                console.error("ThemePropagator: Niri reload failed");
            }
        }
    }

    // ============ Zen Browser ============
    function updateZen(themeId) {
        const colors = zenColors[themeId] || zenColors["gruvbox-dark"];

        const css = `/* Auto-generated by Caelestia ThemePropagator
 * Do not edit - this file is overwritten on theme change
 */

:root {
    --caelestia-bg: ${colors.bg};
    --caelestia-fg: ${colors.fg};
    --caelestia-primary: ${colors.primary};
    --caelestia-secondary: ${colors.secondary};
    --caelestia-accent: ${colors.accent};

    /* Apply to browser UI */
    --toolbar-bgcolor: ${colors.bg} !important;
    --toolbar-color: ${colors.fg} !important;
    --lwt-accent-color: ${colors.primary} !important;
    --lwt-text-color: ${colors.fg} !important;
}

/* Tab bar styling */
#TabsToolbar {
    background-color: ${colors.bg} !important;
}

.tab-background {
    background-color: ${colors.bg} !important;
}

.tab-background[selected="true"] {
    background-color: ${colors.primary} !important;
}

/* URL bar */
#urlbar-background {
    background-color: ${colors.bg} !important;
}

#urlbar-input {
    color: ${colors.fg} !important;
}
`;
        zenCss.setText(css);
    }

    FileView {
        id: zenCss
        // Zen browser profile path - may need adjustment
        path: `${Paths.home}/.zen/3bexths2.Default Profile/chrome/userChrome.css`
        onTextChanged: {
            console.log("ThemePropagator: Zen userChrome.css updated (restart browser to apply)");
        }
    }

    Component.onCompleted: {
        // Ensure directories exist
        ensureDirsProc.running = true;
    }

    Process {
        id: ensureDirsProc
        command: ["bash", "-c", `
            mkdir -p "${Paths.home}/.config/ghostty"
            mkdir -p "${Paths.state}"
            mkdir -p "${Paths.home}/.zen/3bexths2.Default Profile/chrome"
        `]
        onExited: {
            // Propagate initial theme after ensuring directories
            Qt.callLater(() => root.propagateTheme());
        }
    }
}
