pragma Singleton

import qs.services
import qs.utils
import Quickshell
import Quickshell.Io
import QtQuick

Singleton {
    id: root

    // Theme ID to Ghostty theme mapping
    readonly property var ghosttyThemes: ({
        "gruvbox-dark": "Gruvbox Dark",
        "gruvbox-light": "Gruvbox Light"
    })

    // Theme ID to NvChad theme mapping
    readonly property var nvimThemes: ({
        "gruvbox-dark": "gruvbox",
        "gruvbox-light": "gruvbox_light"
    })

    // Zen browser CSS variables per theme
    readonly property var zenColors: ({
        "gruvbox-dark": {
            bg: "#1d2021",
            fg: "#ebdbb2",
            primary: "#d79921",
            secondary: "#689d6a",
            accent: "#b16286"
        },
        "gruvbox-light": {
            bg: "#fbf1c7",
            fg: "#3c3836",
            primary: "#b57614",
            secondary: "#427b58",
            accent: "#8f3f71"
        }
    })

    // Connect to theme changes
    Connections {
        target: Theme
        function onThemeChanged() {
            root.propagateTheme();
        }
    }

    function propagateTheme() {
        const themeId = Theme.currentThemeId;
        console.log("ThemePropagator: Propagating theme:", themeId);

        updateGhostty(themeId);
        updateNeovim(themeId);
        updateZen(themeId);
        // Note: Niri border colors are static (defined in programs.niri.settings)
        // Changing them requires a NixOS rebuild
    }

    // ============ Ghostty ============
    function updateGhostty(themeId) {
        const themeName = ghosttyThemes[themeId] || "Gruvbox Dark";
        const configContent = `# Auto-generated by Caelestia ThemePropagator
# Do not edit - this file is overwritten on theme change
theme = ${themeName}
`;
        ghosttyConfig.setText(configContent);
    }

    FileView {
        id: ghosttyConfig
        path: `${Paths.home}/.config/ghostty/theme.conf`
        onTextChanged: {
            // After writing, send SIGUSR1 to ghostty for live reload
            ghosttyReloadProc.running = true;
        }
    }

    Process {
        id: ghosttyReloadProc
        command: ["pkill", "-USR1", "ghostty"]
        onExited: (exitCode, exitStatus) => {
            if (exitCode === 0) {
                console.log("ThemePropagator: Ghostty theme reloaded");
            }
        }
    }

    // ============ Neovim ============
    function updateNeovim(themeId) {
        const themeName = nvimThemes[themeId] || "gruvbox";
        const stateContent = JSON.stringify({
            theme: themeName,
            themeId: themeId,
            timestamp: Date.now()
        }, null, 2);
        nvimState.setText(stateContent);
    }

    FileView {
        id: nvimState
        path: `${Paths.state}/nvim-theme.json`
        onTextChanged: {
            // After writing state, send command to nvim via socket
            nvimReloadProc.running = true;
        }
    }

    Process {
        id: nvimReloadProc
        command: ["bash", "-c", `
            for sock in /tmp/nvim*.sock /run/user/$(id -u)/nvim*.sock; do
                [ -S "$sock" ] && nvim --server "$sock" --remote-send '<Cmd>lua require("caelestia-theme").reload()<CR>' 2>/dev/null
            done
        `]
        onExited: (exitCode, exitStatus) => {
            console.log("ThemePropagator: Neovim reload attempted");
        }
    }

    // ============ Zen Browser ============
    function updateZen(themeId) {
        const colors = zenColors[themeId] || zenColors["gruvbox-dark"];

        const css = `/* Auto-generated by Caelestia ThemePropagator
 * Do not edit - this file is overwritten on theme change
 */

:root {
    --caelestia-bg: ${colors.bg};
    --caelestia-fg: ${colors.fg};
    --caelestia-primary: ${colors.primary};
    --caelestia-secondary: ${colors.secondary};
    --caelestia-accent: ${colors.accent};

    /* Apply to browser UI */
    --toolbar-bgcolor: ${colors.bg} !important;
    --toolbar-color: ${colors.fg} !important;
    --lwt-accent-color: ${colors.primary} !important;
    --lwt-text-color: ${colors.fg} !important;
}

/* Tab bar styling */
#TabsToolbar {
    background-color: ${colors.bg} !important;
}

.tab-background {
    background-color: ${colors.bg} !important;
}

.tab-background[selected="true"] {
    background-color: ${colors.primary} !important;
}

/* URL bar */
#urlbar-background {
    background-color: ${colors.bg} !important;
}

#urlbar-input {
    color: ${colors.fg} !important;
}
`;
        zenCss.setText(css);
    }

    FileView {
        id: zenCss
        // Zen browser profile path - may need adjustment
        path: `${Paths.home}/.zen/3bexths2.Default Profile/chrome/userChrome.css`
        onTextChanged: {
            console.log("ThemePropagator: Zen userChrome.css updated (restart browser to apply)");
        }
    }

    Component.onCompleted: {
        // Ensure directories exist
        ensureDirsProc.running = true;
    }

    Process {
        id: ensureDirsProc
        command: ["bash", "-c", `
            mkdir -p "${Paths.home}/.config/ghostty"
            mkdir -p "${Paths.state}"
            mkdir -p "${Paths.home}/.zen/3bexths2.Default Profile/chrome"
        `]
        onExited: {
            // Propagate initial theme after ensuring directories
            Qt.callLater(() => root.propagateTheme());
        }
    }
}
