{ config, lib, pkgs, nix-colors, ... }:

let
  # Import all theme definitions
  themes = {
    gruvbox-light = import ../../themes/gruvbox-light.nix { inherit nix-colors; };
    gruvbox-dark = import ../../themes/gruvbox-dark.nix { inherit nix-colors; };
    catppuccin-mocha = import ../../themes/catppuccin-mocha.nix { inherit nix-colors; };
    kanagawa = import ../../themes/kanagawa.nix { inherit nix-colors; };
    rose-pine = import ../../themes/rose-pine.nix { inherit nix-colors; };
    tokyonight = import ../../themes/tokyonight.nix { inherit nix-colors; };
  };

  themeNames = builtins.attrNames themes;
  defaultTheme = "gruvbox-light";

  # Generate waybar CSS for a theme
  mkWaybarCss = theme: ''
    /* Theme: ${theme.name} */
    * {
      font-family: "JetBrainsMono Nerd Font", monospace;
      font-size: 14px;
    }

    window#waybar {
      background-color: #${theme.palette.base00};
      color: #${theme.palette.base05};
      border-bottom: 2px solid #${theme.palette.base0D};
    }

    #clock {
      padding: 0 12px;
      color: #${theme.palette.base05};
    }

    #workspaces button {
      padding: 0 8px;
      color: #${theme.palette.base04};
      background: transparent;
      border: none;
      border-radius: 0;
    }

    #workspaces button.focused,
    #workspaces button.active {
      color: #${theme.palette.base00};
      background-color: #${theme.palette.base0D};
    }

    #workspaces button:hover {
      background-color: #${theme.palette.base02};
    }

    #network {
      padding: 0 12px;
      color: #${theme.palette.base0B};
    }

    #network.disconnected {
      color: #${theme.palette.base08};
    }
  '';

  # Generate ghostty theme file
  mkGhosttyTheme = theme: ''
    # Theme: ${theme.name}
    background = ${theme.palette.base00}
    foreground = ${theme.palette.base05}
    cursor-color = ${theme.palette.base05}
    selection-background = ${theme.palette.base02}
    selection-foreground = ${theme.palette.base05}

    # Normal colors
    palette = 0=#${theme.palette.base00}
    palette = 1=#${theme.palette.base08}
    palette = 2=#${theme.palette.base0B}
    palette = 3=#${theme.palette.base0A}
    palette = 4=#${theme.palette.base0D}
    palette = 5=#${theme.palette.base0E}
    palette = 6=#${theme.palette.base0C}
    palette = 7=#${theme.palette.base05}

    # Bright colors
    palette = 8=#${theme.palette.base03}
    palette = 9=#${theme.palette.base08}
    palette = 10=#${theme.palette.base0B}
    palette = 11=#${theme.palette.base0A}
    palette = 12=#${theme.palette.base0D}
    palette = 13=#${theme.palette.base0E}
    palette = 14=#${theme.palette.base0C}
    palette = 15=#${theme.palette.base07}
  '';

  # Generate mako config for a theme
  mkMakoConf = theme: ''
    # Theme: ${theme.name}
    font=JetBrainsMono Nerd Font 11
    background-color=#${theme.palette.base00}
    text-color=#${theme.palette.base05}
    border-color=#${theme.palette.base0D}
    border-size=2
    border-radius=8
    padding=12
    default-timeout=5000
    max-visible=3

    [urgency=low]
    border-color=#${theme.palette.base03}

    [urgency=high]
    border-color=#${theme.palette.base08}
    default-timeout=0
  '';

  # Generate fuzzel config for a theme
  mkFuzzelIni = theme: ''
    # Theme: ${theme.name}
    [main]
    font=JetBrainsMono Nerd Font:size=12
    prompt="❯ "
    icon-theme=Papirus
    layer=overlay

    [colors]
    background=${theme.palette.base00}ff
    text=${theme.palette.base05}ff
    match=${theme.palette.base0D}ff
    selection=${theme.palette.base02}ff
    selection-text=${theme.palette.base05}ff
    selection-match=${theme.palette.base0D}ff
    border=${theme.palette.base0D}ff

    [border]
    width=2
    radius=8
  '';

  # Generate starship palette section for a theme
  mkStarshipPalette = theme: ''
    [palettes.${theme.name}]
    base00 = "#${theme.palette.base00}"
    base01 = "#${theme.palette.base01}"
    base02 = "#${theme.palette.base02}"
    base03 = "#${theme.palette.base03}"
    base04 = "#${theme.palette.base04}"
    base05 = "#${theme.palette.base05}"
    base06 = "#${theme.palette.base06}"
    base07 = "#${theme.palette.base07}"
    base08 = "#${theme.palette.base08}"
    base09 = "#${theme.palette.base09}"
    base0A = "#${theme.palette.base0A}"
    base0B = "#${theme.palette.base0B}"
    base0C = "#${theme.palette.base0C}"
    base0D = "#${theme.palette.base0D}"
    base0E = "#${theme.palette.base0E}"
    base0F = "#${theme.palette.base0F}"
  '';

  # Generate nvim active-theme.lua for a theme
  mkNvimTheme = theme: ''
    -- Theme: ${theme.name}
    -- This file is generated by theming.nix and symlinked by theme-switch
    return {
      name = "${theme.name}",
      polarity = "${theme.polarity}",
      palette = {
        base00 = "#${theme.palette.base00}",
        base01 = "#${theme.palette.base01}",
        base02 = "#${theme.palette.base02}",
        base03 = "#${theme.palette.base03}",
        base04 = "#${theme.palette.base04}",
        base05 = "#${theme.palette.base05}",
        base06 = "#${theme.palette.base06}",
        base07 = "#${theme.palette.base07}",
        base08 = "#${theme.palette.base08}",
        base09 = "#${theme.palette.base09}",
        base0A = "#${theme.palette.base0A}",
        base0B = "#${theme.palette.base0B}",
        base0C = "#${theme.palette.base0C}",
        base0D = "#${theme.palette.base0D}",
        base0E = "#${theme.palette.base0E}",
        base0F = "#${theme.palette.base0F}",
      }
    }
  '';

  # Generate all per-theme config files
  themeConfigs = lib.mapAttrs' (name: theme: {
    name = "waybar/themes/${name}.css";
    value = { text = mkWaybarCss theme; };
  }) themes // lib.mapAttrs' (name: theme: {
    name = "ghostty/themes/${name}";
    value = { text = mkGhosttyTheme theme; };
  }) themes // lib.mapAttrs' (name: theme: {
    name = "mako/themes/${name}.conf";
    value = { text = mkMakoConf theme; };
  }) themes // lib.mapAttrs' (name: theme: {
    name = "fuzzel/themes/${name}.ini";
    value = { text = mkFuzzelIni theme; };
  }) themes // lib.mapAttrs' (name: theme: {
    name = "nvim-theme/${name}.lua";
    value = { text = mkNvimTheme theme; };
  }) themes;

  # Build starship.toml with all palette definitions
  starshipConfig = ''
    # Starship prompt configuration
    # Palettes are defined per-theme, palette_name is set by theme-switch

    format = """
    [](base0D)\
    $os\
    [](bg:base0A fg:base0D)\
    $directory\
    [](fg:base0A bg:base0B)\
    $git_branch\
    $git_status\
    [](fg:base0B bg:base02)\
    $fill\
    [](fg:base02 bg:base02)\
    $cmd_duration\
    [](fg:base03 bg:base02)\
    $time\
    [](fg:base03)\
    $line_break\
    $character"""

    palette = "${defaultTheme}"

    [os]
    disabled = false
    style = "bg:base0D fg:base00"
    format = "[ $symbol ]($style)"

    [os.symbols]
    NixOS = ""

    [directory]
    style = "bg:base0A fg:base00"
    format = "[ $path ]($style)"
    truncation_length = 3
    truncation_symbol = "…/"

    [git_branch]
    symbol = ""
    style = "bg:base0B fg:base00"
    format = "[ $symbol $branch ]($style)"

    [git_status]
    style = "bg:base0B fg:base00"
    format = "[$all_status$ahead_behind]($style)"
    ahead = "↑"
    behind = "↓"
    modified = "!"
    untracked = "?"
    staged = "+"

    [fill]
    symbol = " "

    [cmd_duration]
    min_time = 500
    style = "bg:base02 fg:base05"
    format = "[⏱ $duration ]($style)"

    [time]
    disabled = false
    time_format = "%H:%M"
    style = "bg:base03 fg:base05"
    format = "[  $time ]($style)"

    [character]
    success_symbol = "[λ](bold base0B)"
    error_symbol = "[λ](bold base08)"

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: theme: mkStarshipPalette theme) themes)}
  '';

  # Theme metadata for scripts
  themeMetaJson = builtins.toJSON (lib.mapAttrs (name: theme: {
    inherit (theme) name polarity wallpaper;
  }) themes);

  # theme-switch script
  themeSwitchScript = pkgs.writeShellScriptBin "theme-switch" ''
    set -euo pipefail

    THEME="''${1:-}"
    THEMES=(${lib.concatStringsSep " " themeNames})
    CONFIG_DIR="$HOME/.config"

    if [[ -z "$THEME" ]]; then
      echo "Usage: theme-switch <theme-name>"
      echo "Available themes: ''${THEMES[*]}"
      exit 1
    fi

    # Validate theme exists
    VALID=0
    for t in "''${THEMES[@]}"; do
      if [[ "$t" == "$THEME" ]]; then
        VALID=1
        break
      fi
    done

    if [[ $VALID -eq 0 ]]; then
      echo "Error: Unknown theme '$THEME'"
      echo "Available themes: ''${THEMES[*]}"
      exit 1
    fi

    echo "Switching to theme: $THEME"

    # Update symlinks
    ln -sf "$CONFIG_DIR/waybar/themes/$THEME.css" "$CONFIG_DIR/waybar/colors.css"
    ln -sf "$CONFIG_DIR/ghostty/themes/$THEME" "$CONFIG_DIR/ghostty/theme"
    ln -sf "$CONFIG_DIR/mako/themes/$THEME.conf" "$CONFIG_DIR/mako/config"
    ln -sf "$CONFIG_DIR/fuzzel/themes/$THEME.ini" "$CONFIG_DIR/fuzzel/fuzzel.ini"
    ln -sf "$CONFIG_DIR/nvim-theme/$THEME.lua" "$CONFIG_DIR/nvim-theme/active.lua"

    # Update starship palette
    ${pkgs.gnused}/bin/sed -i "s/^palette = .*/palette = \"$THEME\"/" "$CONFIG_DIR/starship.toml"

    # Reload services
    ${pkgs.procps}/bin/pkill -SIGUSR2 waybar || true
    ${pkgs.mako}/bin/makoctl reload || true
    ${pkgs.procps}/bin/pkill -SIGUSR2 ghostty || true

    # Best-effort nvim reload
    NVIM_SOCKET="''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/nvim.sock"
    if [[ -S "$NVIM_SOCKET" ]]; then
      ${pkgs.neovim}/bin/nvim --server "$NVIM_SOCKET" --remote-send ':luafile ~/.config/nvim-theme/active.lua<CR>' 2>/dev/null || true
    fi

    echo "Theme switched to: $THEME"
  '';

  # theme-pick script (fuzzel menu) - switches theme only, no wallpaper
  themePickScript = pkgs.writeShellScriptBin "theme-pick" ''
    THEMES="${lib.concatStringsSep "\\n" themeNames}"
    SELECTED=$(printf "$THEMES" | ${pkgs.fuzzel}/bin/fuzzel --dmenu --prompt "Theme: ")

    if [[ -n "$SELECTED" ]]; then
      ${themeSwitchScript}/bin/theme-switch "$SELECTED"
    fi
  '';

  # wallpaper-switch script - sets wallpaper and auto-switches theme
  wallpaperSwitchScript = pkgs.writeShellScriptBin "wallpaper-switch" ''
    set -euo pipefail

    WALLPAPER_NAME="''${1:-}"
    WALLPAPER_CONFIG="/home/kamdyns/nixos-config/wallpapers/config.json"

    if [[ -z "$WALLPAPER_NAME" ]]; then
      echo "Usage: wallpaper-switch <wallpaper-name>"
      echo "Available wallpapers:"
      ${pkgs.jq}/bin/jq -r 'keys[]' "$WALLPAPER_CONFIG"
      exit 1
    fi

    if [[ ! -f "$WALLPAPER_CONFIG" ]]; then
      echo "Error: Wallpaper config not found at $WALLPAPER_CONFIG"
      exit 1
    fi

    # Get wallpaper path and theme
    WALLPAPER_PATH=$(${pkgs.jq}/bin/jq -r ".[\"$WALLPAPER_NAME\"].path // empty" "$WALLPAPER_CONFIG")
    THEME=$(${pkgs.jq}/bin/jq -r ".[\"$WALLPAPER_NAME\"].theme // empty" "$WALLPAPER_CONFIG")

    if [[ -z "$WALLPAPER_PATH" ]]; then
      echo "Error: Unknown wallpaper '$WALLPAPER_NAME'"
      echo "Available wallpapers:"
      ${pkgs.jq}/bin/jq -r 'keys[]' "$WALLPAPER_CONFIG"
      exit 1
    fi

    echo "Wallpaper: $WALLPAPER_NAME → $THEME"

    # Set wallpaper
    if [[ -f "$WALLPAPER_PATH" ]]; then
      ${pkgs.awww}/bin/awww img "$WALLPAPER_PATH" --transition-type wipe --transition-duration 1
    else
      echo "Warning: Wallpaper file not found at $WALLPAPER_PATH"
    fi

    # Switch theme
    ${themeSwitchScript}/bin/theme-switch "$THEME"
  '';

  # wallpaper-pick script (fuzzel menu) - primary interface
  wallpaperPickScript = pkgs.writeShellScriptBin "wallpaper-pick" ''
    WALLPAPER_CONFIG="/home/kamdyns/nixos-config/wallpapers/config.json"
    WALLPAPERS=$(${pkgs.jq}/bin/jq -r 'keys[]' "$WALLPAPER_CONFIG")
    SELECTED=$(printf "%s" "$WALLPAPERS" | ${pkgs.fuzzel}/bin/fuzzel --dmenu --prompt "Wallpaper: ")

    if [[ -n "$SELECTED" ]]; then
      ${wallpaperSwitchScript}/bin/wallpaper-switch "$SELECTED"
    fi
  '';

  # power-menu script
  powerMenuScript = pkgs.writeShellScriptBin "power-menu" ''
    OPTIONS="logout\nreboot\nshutdown\nsuspend\ncancel"
    SELECTED=$(printf "$OPTIONS" | ${pkgs.fuzzel}/bin/fuzzel --dmenu --prompt "Power: ")

    case "$SELECTED" in
      logout)
        ${pkgs.niri}/bin/niri msg action quit
        ;;
      reboot)
        systemctl reboot
        ;;
      shutdown)
        systemctl poweroff
        ;;
      suspend)
        systemctl suspend
        ;;
      cancel|"")
        ;;
    esac
  '';

in
{
  # Generate all themed config files
  xdg.configFile = themeConfigs // {
    # Starship config with all palettes
    "starship.toml".text = starshipConfig;
  };

  # Add scripts to PATH
  home.packages = [
    themeSwitchScript
    themePickScript
    wallpaperSwitchScript
    wallpaperPickScript
    powerMenuScript
  ];

  # Create initial symlinks for default theme on activation
  home.activation.setupThemeSymlinks = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p $HOME/.config/waybar
    $DRY_RUN_CMD mkdir -p $HOME/.config/ghostty
    $DRY_RUN_CMD mkdir -p $HOME/.config/mako
    $DRY_RUN_CMD mkdir -p $HOME/.config/fuzzel
    $DRY_RUN_CMD mkdir -p $HOME/.config/nvim-theme

    # Only create symlinks if they don't exist (preserve user's current theme choice)
    if [[ ! -L $HOME/.config/waybar/colors.css ]]; then
      $DRY_RUN_CMD ln -sf $HOME/.config/waybar/themes/${defaultTheme}.css $HOME/.config/waybar/colors.css
    fi
    if [[ ! -L $HOME/.config/ghostty/theme ]]; then
      $DRY_RUN_CMD ln -sf $HOME/.config/ghostty/themes/${defaultTheme} $HOME/.config/ghostty/theme
    fi
    if [[ ! -L $HOME/.config/mako/config ]]; then
      $DRY_RUN_CMD ln -sf $HOME/.config/mako/themes/${defaultTheme}.conf $HOME/.config/mako/config
    fi
    if [[ ! -L $HOME/.config/fuzzel/fuzzel.ini ]]; then
      $DRY_RUN_CMD ln -sf $HOME/.config/fuzzel/themes/${defaultTheme}.ini $HOME/.config/fuzzel/fuzzel.ini
    fi
    if [[ ! -L $HOME/.config/nvim-theme/active.lua ]]; then
      $DRY_RUN_CMD ln -sf $HOME/.config/nvim-theme/${defaultTheme}.lua $HOME/.config/nvim-theme/active.lua
    fi
  '';
}
