-- Apply a base16 palette as nvim highlights.
-- Used as the fallback colorscheme for rice themes that don't have a dedicated
-- nvim plugin. The palette comes straight from ~/.config/nvim-theme/active.lua.

local M = {}

local function hl(group, spec)
    vim.api.nvim_set_hl(0, group, spec)
end

function M.apply(theme)
    local p = theme.palette
    local bg = theme.polarity == "light" and "light" or "dark"

    vim.cmd "hi clear"
    if vim.fn.exists "syntax_on" == 1 then
        vim.cmd "syntax reset"
    end
    vim.opt.background = bg
    vim.g.colors_name = "rice-base16"

    -- UI
    hl("Normal", { fg = p.base05, bg = p.base00 })
    hl("NormalFloat", { fg = p.base05, bg = p.base01 })
    hl("FloatBorder", { fg = p.base0D, bg = p.base01 })
    hl("FloatTitle", { fg = p.base0D, bg = p.base01, bold = true })
    hl("Cursor", { fg = p.base00, bg = p.base05 })
    hl("CursorLine", { bg = p.base01 })
    hl("CursorLineNr", { fg = p.base0A, bg = p.base01, bold = true })
    hl("LineNr", { fg = p.base03 })
    hl("SignColumn", { fg = p.base03, bg = p.base00 })
    hl("ColorColumn", { bg = p.base01 })
    hl("VertSplit", { fg = p.base02 })
    hl("WinSeparator", { fg = p.base02 })
    hl("StatusLine", { fg = p.base05, bg = p.base01 })
    hl("StatusLineNC", { fg = p.base04, bg = p.base01 })
    hl("WinBar", { fg = p.base05, bg = p.base01, bold = true })
    hl("WinBarNC", { fg = p.base04, bg = p.base01 })
    hl("TabLine", { fg = p.base04, bg = p.base01 })
    hl("TabLineSel", { fg = p.base05, bg = p.base02 })
    hl("TabLineFill", { bg = p.base01 })
    hl("Pmenu", { fg = p.base05, bg = p.base01 })
    hl("PmenuSel", { fg = p.base05, bg = p.base02, bold = true })
    hl("PmenuSbar", { bg = p.base02 })
    hl("PmenuThumb", { bg = p.base04 })
    hl("Visual", { bg = p.base02 })
    hl("VisualNOS", { bg = p.base02 })
    hl("Search", { fg = p.base00, bg = p.base0A })
    hl("IncSearch", { fg = p.base00, bg = p.base09 })
    hl("CurSearch", { fg = p.base00, bg = p.base09 })
    hl("MatchParen", { fg = p.base0A, bold = true, underline = true })
    hl("Folded", { fg = p.base03, bg = p.base01 })
    hl("FoldColumn", { fg = p.base03, bg = p.base00 })
    hl("NonText", { fg = p.base03 })
    hl("Whitespace", { fg = p.base02 })
    hl("EndOfBuffer", { fg = p.base00 })
    hl("Directory", { fg = p.base0D })
    hl("Title", { fg = p.base0D, bold = true })
    hl("Conceal", { fg = p.base0D })
    hl("SpecialKey", { fg = p.base03 })
    hl("ErrorMsg", { fg = p.base08 })
    hl("WarningMsg", { fg = p.base0A })
    hl("ModeMsg", { fg = p.base0B })
    hl("MoreMsg", { fg = p.base0B })
    hl("Question", { fg = p.base0B })
    hl("WildMenu", { fg = p.base00, bg = p.base05 })
    hl("QuickFixLine", { bg = p.base02 })

    -- Syntax (legacy groups, still used as fallbacks by treesitter)
    hl("Comment", { fg = p.base03, italic = true })
    hl("Constant", { fg = p.base09 })
    hl("String", { fg = p.base0B })
    hl("Character", { fg = p.base08 })
    hl("Number", { fg = p.base09 })
    hl("Boolean", { fg = p.base09 })
    hl("Float", { fg = p.base09 })
    hl("Identifier", { fg = p.base08 })
    hl("Function", { fg = p.base0D })
    hl("Statement", { fg = p.base0E })
    hl("Conditional", { fg = p.base0E })
    hl("Repeat", { fg = p.base0E })
    hl("Label", { fg = p.base0A })
    hl("Operator", { fg = p.base05 })
    hl("Keyword", { fg = p.base0E })
    hl("Exception", { fg = p.base08 })
    hl("PreProc", { fg = p.base0A })
    hl("Include", { fg = p.base0D })
    hl("Define", { fg = p.base0E })
    hl("Macro", { fg = p.base08 })
    hl("PreCondit", { fg = p.base0A })
    hl("Type", { fg = p.base0A })
    hl("StorageClass", { fg = p.base0A })
    hl("Structure", { fg = p.base0E })
    hl("Typedef", { fg = p.base0A })
    hl("Special", { fg = p.base0C })
    hl("SpecialChar", { fg = p.base0F })
    hl("Tag", { fg = p.base0A })
    hl("Delimiter", { fg = p.base0F })
    hl("SpecialComment", { fg = p.base0C })
    hl("Debug", { fg = p.base08 })
    hl("Underlined", { fg = p.base08, underline = true })
    hl("Ignore", { fg = p.base00 })
    hl("Error", { fg = p.base00, bg = p.base08 })
    hl("Todo", { fg = p.base0A, bg = p.base01, bold = true })

    -- Diff
    hl("DiffAdd", { fg = p.base0B, bg = p.base01 })
    hl("DiffChange", { fg = p.base0E, bg = p.base01 })
    hl("DiffDelete", { fg = p.base08, bg = p.base01 })
    hl("DiffText", { fg = p.base0D, bg = p.base01 })

    -- Diagnostics
    hl("DiagnosticError", { fg = p.base08 })
    hl("DiagnosticWarn", { fg = p.base0A })
    hl("DiagnosticInfo", { fg = p.base0D })
    hl("DiagnosticHint", { fg = p.base0C })
    hl("DiagnosticOk", { fg = p.base0B })
    hl("DiagnosticUnderlineError", { sp = p.base08, undercurl = true })
    hl("DiagnosticUnderlineWarn", { sp = p.base0A, undercurl = true })
    hl("DiagnosticUnderlineInfo", { sp = p.base0D, undercurl = true })
    hl("DiagnosticUnderlineHint", { sp = p.base0C, undercurl = true })
    hl("DiagnosticVirtualTextError", { fg = p.base08, bg = p.base01 })
    hl("DiagnosticVirtualTextWarn", { fg = p.base0A, bg = p.base01 })
    hl("DiagnosticVirtualTextInfo", { fg = p.base0D, bg = p.base01 })
    hl("DiagnosticVirtualTextHint", { fg = p.base0C, bg = p.base01 })

    -- Spell
    hl("SpellBad", { sp = p.base08, undercurl = true })
    hl("SpellCap", { sp = p.base0D, undercurl = true })
    hl("SpellLocal", { sp = p.base0C, undercurl = true })
    hl("SpellRare", { sp = p.base0E, undercurl = true })

    -- Treesitter (subset; legacy fallbacks cover the rest)
    hl("@variable", { fg = p.base05 })
    hl("@variable.builtin", { fg = p.base09 })
    hl("@variable.parameter", { fg = p.base08 })
    hl("@variable.member", { fg = p.base05 })
    hl("@property", { fg = p.base0D })
    hl("@field", { fg = p.base0D })
    hl("@constant", { fg = p.base09 })
    hl("@constant.builtin", { fg = p.base09 })
    hl("@constant.macro", { fg = p.base08 })
    hl("@string", { fg = p.base0B })
    hl("@string.escape", { fg = p.base0C })
    hl("@string.special", { fg = p.base0C })
    hl("@character", { fg = p.base08 })
    hl("@number", { fg = p.base09 })
    hl("@boolean", { fg = p.base09 })
    hl("@float", { fg = p.base09 })
    hl("@function", { fg = p.base0D })
    hl("@function.builtin", { fg = p.base0D })
    hl("@function.call", { fg = p.base0D })
    hl("@function.macro", { fg = p.base08 })
    hl("@function.method", { fg = p.base0D })
    hl("@constructor", { fg = p.base0A })
    hl("@operator", { fg = p.base05 })
    hl("@keyword", { fg = p.base0E })
    hl("@keyword.function", { fg = p.base0E })
    hl("@keyword.operator", { fg = p.base0E })
    hl("@keyword.return", { fg = p.base0E })
    hl("@keyword.import", { fg = p.base0D })
    hl("@keyword.conditional", { fg = p.base0E })
    hl("@keyword.repeat", { fg = p.base0E })
    hl("@keyword.exception", { fg = p.base08 })
    hl("@type", { fg = p.base0A })
    hl("@type.builtin", { fg = p.base0A })
    hl("@type.definition", { fg = p.base0A })
    hl("@attribute", { fg = p.base0A })
    hl("@punctuation", { fg = p.base05 })
    hl("@punctuation.bracket", { fg = p.base05 })
    hl("@punctuation.delimiter", { fg = p.base05 })
    hl("@punctuation.special", { fg = p.base0F })
    hl("@comment", { fg = p.base03, italic = true })
    hl("@comment.todo", { fg = p.base0A, bold = true })
    hl("@comment.error", { fg = p.base08, bold = true })
    hl("@comment.warning", { fg = p.base0A, bold = true })
    hl("@comment.note", { fg = p.base0D, bold = true })
    hl("@tag", { fg = p.base0A })
    hl("@tag.attribute", { fg = p.base08 })
    hl("@tag.delimiter", { fg = p.base0F })
    hl("@module", { fg = p.base0A })
    hl("@namespace", { fg = p.base0A })
    hl("@markup.heading", { fg = p.base0D, bold = true })
    hl("@markup.strong", { bold = true })
    hl("@markup.italic", { italic = true })
    hl("@markup.link", { fg = p.base0D, underline = true })
    hl("@markup.link.url", { fg = p.base09, underline = true })
    hl("@markup.raw", { fg = p.base0B })
    hl("@markup.list", { fg = p.base08 })
    hl("@markup.quote", { fg = p.base0C })
    hl("@diff.plus", { fg = p.base0B })
    hl("@diff.minus", { fg = p.base08 })
    hl("@diff.delta", { fg = p.base0E })

    -- LSP semantic tokens
    hl("@lsp.type.namespace", { link = "@namespace" })
    hl("@lsp.type.type", { link = "@type" })
    hl("@lsp.type.class", { link = "@type" })
    hl("@lsp.type.enum", { link = "@type" })
    hl("@lsp.type.interface", { link = "@type" })
    hl("@lsp.type.struct", { link = "@type" })
    hl("@lsp.type.parameter", { link = "@variable.parameter" })
    hl("@lsp.type.variable", { link = "@variable" })
    hl("@lsp.type.property", { link = "@property" })
    hl("@lsp.type.function", { link = "@function" })
    hl("@lsp.type.method", { link = "@function.method" })
    hl("@lsp.type.macro", { link = "@function.macro" })
    hl("@lsp.type.decorator", { link = "@attribute" })

    -- Gitsigns
    hl("GitSignsAdd", { fg = p.base0B, bg = p.base00 })
    hl("GitSignsChange", { fg = p.base0E, bg = p.base00 })
    hl("GitSignsDelete", { fg = p.base08, bg = p.base00 })

    -- nvim-tree
    hl("NvimTreeNormal", { fg = p.base05, bg = p.base01 })
    hl("NvimTreeNormalNC", { fg = p.base05, bg = p.base01 })
    hl("NvimTreeFolderName", { fg = p.base0D })
    hl("NvimTreeOpenedFolderName", { fg = p.base0D, bold = true })
    hl("NvimTreeEmptyFolderName", { fg = p.base04 })
    hl("NvimTreeRootFolder", { fg = p.base0E, bold = true })
    hl("NvimTreeFolderIcon", { fg = p.base0D })
    hl("NvimTreeSpecialFile", { fg = p.base0A })
    hl("NvimTreeExecFile", { fg = p.base0B })
    hl("NvimTreeImageFile", { fg = p.base0E })
    hl("NvimTreeIndentMarker", { fg = p.base03 })
    hl("NvimTreeGitDirty", { fg = p.base0A })
    hl("NvimTreeGitNew", { fg = p.base0B })
    hl("NvimTreeGitDeleted", { fg = p.base08 })
    hl("NvimTreeGitStaged", { fg = p.base0B })

    -- Telescope
    hl("TelescopeNormal", { fg = p.base05, bg = p.base01 })
    hl("TelescopeBorder", { fg = p.base0D, bg = p.base01 })
    hl("TelescopePromptNormal", { fg = p.base05, bg = p.base02 })
    hl("TelescopePromptBorder", { fg = p.base02, bg = p.base02 })
    hl("TelescopePromptPrefix", { fg = p.base08, bg = p.base02 })
    hl("TelescopePromptTitle", { fg = p.base00, bg = p.base08, bold = true })
    hl("TelescopePreviewTitle", { fg = p.base00, bg = p.base0B, bold = true })
    hl("TelescopeResultsTitle", { fg = p.base01, bg = p.base01 })
    hl("TelescopeSelection", { bg = p.base02 })
    hl("TelescopeMatching", { fg = p.base0A, bold = true })

    -- WhichKey
    hl("WhichKey", { fg = p.base0D })
    hl("WhichKeyGroup", { fg = p.base0E })
    hl("WhichKeyDesc", { fg = p.base05 })
    hl("WhichKeySeparator", { fg = p.base03 })
    hl("WhichKeyFloat", { bg = p.base01 })
    hl("WhichKeyBorder", { fg = p.base0D, bg = p.base01 })
end

return M
